os: Visual Studio 2015
version: 1.0.0.{build}

clone_folder: c:\projects\gtest-runner

branches:
  except:
    - documentation
    
configuration:
  - Debug
  - Release
  
environment:
  matrix:
  - VS_GEN: Visual Studio 12 2013
    QTDIR: C:\Qt\5.6\msvc2013
    EXT: win32
  - VS_GEN: Visual Studio 12 2013 Win64
    QTDIR: C:\Qt\5.6\msvc2013_64
    EXT: win64
  global:
    PWD:
      secure: 9z2ZbAlRhD7hRqEYrmxNMg==

matrix:
  fast_finish: true
  
install:
  - set PATH=%PATH%;%QTDIR%\bin;"c:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\Bin\"
  
build_script:
  - md build
  - cd build
  - cmake -Wno-dev -G"%VS_GEN%" ..
  - cmake --build . --config %CONFIGURATION%
  - cmake --build . --target PACKAGE --config %CONFIGURATION%
  - cd ..

artifacts:
  - path: build
    name: windows_portable
    type: zip
